version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - JWT_SECRET=your_jwt_secret_key_here
      - MONGODB_URI=mongodb+srv://hugoev:${DB_PASSWORD}@marketplacedb.lan06.mongodb.net/?retryWrites=true&w=majority&appName=marketplaceDB
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 